<?xml version="1.0"?>
<package format="3">
  <name>scx_slam_executor</name>
  <version>0.1.0</version>
  <description>ROS 2 executor integration for scx_slam_fresh.</description>
  <maintainer email="samehsmh@gmail.com">Sameh S. Hassan</maintainer>
  <license>GPL-2.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
