/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Userspace loader + monitor for scx_slam_fresh.
 *
 * Build expects build/scx_slam_fresh.skel.h generated by bpftool.
 */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <stdarg.h>

#include <bpf/libbpf.h>

#include "../include/scx_slam_fresh_shared.h"
#include "scx_slam_fresh.skel.h"

static volatile sig_atomic_t g_exiting;

static void on_sigint(int signo)
{
    (void)signo;
    g_exiting = 1;
}

static int bump_memlock_rlimit(void)
{
    struct rlimit r = {RLIM_INFINITY, RLIM_INFINITY};
    return setrlimit(RLIMIT_MEMLOCK, &r);
}

static int libbpf_print_fn(enum libbpf_print_level level,
                           const char *format, va_list args)
{
    if (level == LIBBPF_DEBUG)
        return 0;
    return vfprintf(stderr, format, args);
}

static int handle_evt(void *ctx, void *data, size_t data_sz)
{
    (void)ctx;

    if (data_sz < sizeof(struct slam_evt))
        return 0;

    const struct slam_evt *e = (const struct slam_evt *)data;

    const char *kind = "UNKNOWN";
    switch (e->kind) {
    case SLAM_EVT_DEADLINE_MISS:  kind = "DEADLINE_MISS"; break;
    case SLAM_EVT_BUDGET_OVERRUN: kind = "BUDGET_OVERRUN"; break;
    case SLAM_EVT_STALE_DEMOTION: kind = "STALE_DEMOTION"; break;
    case SLAM_EVT_BUDGET_DEMOTION: kind = "BUDGET_DEMOTION"; break;
    default: break;
    }

    printf("[evt] %s stage=%u job=%llu pid_tgid=0x%llx age=%.3fms exec=%.3fms\n",
           kind,
           e->stage_id,
           (unsigned long long)e->job_id,
           (unsigned long long)e->pid_tgid,
           (double)e->age_ns / 1e6,
           (double)e->exec_ns_in_job / 1e6);
    return 0;
}

static void usage(const char *argv0)
{
    fprintf(stderr,
            "Usage: %s --pin <dir>\n"
            "\n"
            "Example:\n"
            "  sudo %s --pin /sys/fs/bpf/scx_slam_fresh\n",
            argv0, argv0);
}

static int ensure_dir(const char *dir)
{
    struct stat st;
    if (!stat(dir, &st)) {
        if (S_ISDIR(st.st_mode))
            return 0;
        return -ENOTDIR;
    }
    if (mkdir(dir, 0755))
        return -errno;
    return 0;
}

int main(int argc, char **argv)
{
    const char *pin_dir = NULL;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--pin") && i + 1 < argc) {
            pin_dir = argv[++i];
        } else if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
            usage(argv[0]);
            return 0;
        } else {
            usage(argv[0]);
            return 1;
        }
    }

    if (!pin_dir) {
        usage(argv[0]);
        return 1;
    }

    if (bump_memlock_rlimit()) {
        perror("setrlimit(RLIMIT_MEMLOCK)");
        /* keep going; some distros don't need this */
    }

    int err = ensure_dir(pin_dir);
    if (err) {
        fprintf(stderr, "Failed to create pin dir %s: %s\n", pin_dir, strerror(-err));
        return 1;
    }

    libbpf_set_strict_mode(LIBBPF_STRICT_ALL);
    libbpf_set_print(libbpf_print_fn);

    struct scx_slam_fresh_bpf *skel = scx_slam_fresh_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }

    err = scx_slam_fresh_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to load BPF skeleton: %s\n", strerror(-err));
        goto out;
    }

    err = scx_slam_fresh_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF scheduler: %s\n", strerror(-err));
        goto out;
    }

    /* Pin maps so libslamqos and other processes can access them. */
    char path[4096];

    snprintf(path, sizeof(path), "%s/task_hints", pin_dir);
    err = bpf_map__pin(skel->maps.task_hints, path);
    if (err) {
        fprintf(stderr, "Failed to pin task_hints: %s\n", strerror(-err));
        goto out;
    }

    snprintf(path, sizeof(path), "%s/events", pin_dir);
    err = bpf_map__pin(skel->maps.events, path);
    if (err) {
        fprintf(stderr, "Failed to pin events: %s\n", strerror(-err));
        goto out;
    }

    struct ring_buffer *rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
                                              handle_evt, NULL, NULL);
    if (!rb) {
        fprintf(stderr, "Failed to create ring buffer\n");
        err = -ENOMEM;
        goto out;
    }

    signal(SIGINT, on_sigint);
    signal(SIGTERM, on_sigint);

    printf("scx_slam_fresh attached. Maps pinned under: %s\n", pin_dir);
    printf("Press Ctrl-C to stop.\n");

    while (!g_exiting) {
        err = ring_buffer__poll(rb, 100 /*ms*/);
        if (err == -EINTR) {
            err = 0;
            break;
        }
        if (err < 0) {
            fprintf(stderr, "ring_buffer__poll: %s\n", strerror(-err));
            break;
        }
    }

    ring_buffer__free(rb);

out:
    scx_slam_fresh_bpf__destroy(skel);
    return err ? 1 : 0;
}
